### ISSUE TITLE
Support cm13 ! 

### ISSUE THREAD

**Issue by Salamandar** [beli3ver/Paper-FOSS-Theme#20]
Everything is in the title :)

**Comment by beli3ver** [comment]
Could please try to install.
Because friends of mine have 13 and there it works.

**Comment by Salamandar** [comment]
Well the theme manager does not detect the theme... :/

**Comment by beli3ver** [comment]
Ahh OK.
I will fixed it thanks for report.

**Comment by Salamandar** [comment]
Thanks !

**Comment by GitHG22** [comment]
I am using the theme on AICP, with CM Theme Engine. The icon pack appears under the icon section and not under theme packs.

**Comment by beli3ver** [comment]
Yeah.
The reason is that it only support icons and ringtone now.
Maybe next release will have the theme


Am 23. Juni 2016 13:17:43 MESZ, schrieb GitHG22 <notifications@github.com>:
>I am using the theme on AICP, with CM Theme Engine. The icon pack
>appears under the icon section and not under theme packs.
>
>---
>You are receiving this because you were assigned.
>Reply to this email directly or view it on GitHub:
>https://github.com/beli3ver/Paper-FOSS-Theme/issues/20#issuecomment-228019820

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by Salamandar** [comment]
Oh, okay, that explains. Then the issue is real ;)
