### ISSUE TITLE
integrate my appfilter meta repo!

### ISSUE THREAD

**Issue by conrad-heimbold** [beli3ver/Paper-FOSS-Theme#22]
Hi @beli3ver ; 

I made a script and repo; containing (in the end) **all** the PACKAGE_NAMES, ACTIVITY_NAMES and ICON_FILES for **all** FOSS apps on F-Droid: https://github.com/conrad-heimbold/fdroid_apps_theming_data_and_original_icons . So far, my script worked for **1711 apps** (that's really A LOT!); but there are still many missing; unfortunately. 

You can add another git repo completely into your one by adding it as **sub-module** in a sub-folder. 
This way, you don't have to care anymore about getting the latest PACKAGE_NAMES, ACTIVITY_NAMES and ORIGINAL_ICON_FILES; this can be done in a separate repo. 
You can just focus on making the icons!

**Comment by beli3ver** [comment]
Wow.
This is amazing.
I will check it out.


Am 9. August 2017 19:43:38 MESZ schrieb conrad-heimbold <notifications@github.com>:
>Hi @beli3ver ; 
>
>I made a script and repo; containing (in the end) **all** the
>PACKAGE_NAMES, ACTIVITY_NAMES and ICON_FILES for **all** FOSS apps on
>F-Droid:
>https://github.com/conrad-heimbold/fdroid_apps_theming_data_and_original_icons
>. So far, my script worked for **1711 apps** (that's really A LOT!);
>but there are still many missing; unfortunately. 
>
>You can add another git repo completely into your one by adding it as
>**sub-module** in a sub-folder. 
>This way, you don't have to care anymore about getting the latest
>PACKAGE_NAMES, ACTIVITY_NAMES and ORIGINAL_ICON_FILES; this can be done
>in a separate repo. 
>You can just focus on making the icons! 
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/beli3ver/Paper-FOSS-Theme/issues/22

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by beli3ver** [comment]
Do you still update the Repo?
Could you add IzzyOnDroid Repo?

**Comment by conrad-heimbold** [comment]
I am still working on it, but it's not ready for any integration at all.

**Comment by conrad-heimbold** [comment]
github does rate-limiting, so my script isn't very suitable.
