### ISSUE TITLE
Icon Request: Several Apps

### ISSUE THREAD

**Issue by thenanobel** [beli3ver/Paper-FOSS-Theme#27]
| Done | App Name | App ID | Icon in Papirus Repo | 
| --- | --- | --- | --- |
| :white_check_mark: | debDroid | `de.mangelow.debdroid` | `gdebi.svg` |
| :white_check_mark: | Forcastie | `cz.martykan.forecastie` | `weather.svg` |
| :white_check_mark: | Good Weather | `org.asdtm.goodweather` | `weather.svg` |
| :white_check_mark: | MemeTastic | `io.github.gsantner.memetastic` | `mcomix.svg` |
| :white_check_mark: | MineTest | `net.minetest.minetest` | `minetest.svg`|
| :white_check_mark: | Night Screen | `info.papdt.blackblub` | `redshift.svg` |
| :white_check_mark: | Red Moon | `com.jmstudios.redmoon` | `redshift.svg` |
| :white_check_mark: | Simplenote | `com.automattic.simplenote` | `simplenote.svg` |
| :white_check_mark: | Simple Weather | `com.a5corp.weather` | ``weather.svg`` |
| :white_check_mark: | Tethering and Hotspot | `System Software` | `fern-wifi-cracker.svg` |
| :white_check_mark: | Tinfoil for Facebook | `com.danvelazco.fbwrapper` | `facebook.svg` |
| :white_check_mark: | Video Player | `Default Video Player` | `multimedia-video-player.svg` |
| :white_check_mark: | Weather | `de.baumann.weather` | ``weather.svg`` |
| :x: no fdroid app | Wire | `com.wire` | `wire.svg` |

**Comment by beli3ver** [comment]
Please use https://f-droid.org/packages/org.xphnx.iconsubmit/ to send me the appfilter for the videoplayer here-

**Comment by thenanobel** [comment]
Although I told you to use `redshift.svg` as the icon for *Red Moon*. But, now I've found a better icon. It's `marsshooter.svg`. Is it possible this instead of the earlier one.

**Comment by thenanobel** [comment]
<item component="ComponentInfo{com.android.settings/com.android.settings.Settings$SprdTetherSettingsActivity}" drawable="com_android_settings_com_android_settings_Settings$SprdTetherSettingsActivity"/>

    
    <item component="ComponentInfo{com.android.gallery3d/com.sprd.gallery3d.app.VideoActivity}" drawable="com_android_gallery3d_com_sprd_gallery3d_app_VideoActivity"/>
