### ISSUE TITLE
CyanogenMod Design App crashs

### ISSUE THREAD

**Issue by conrad-heimbold** [beli3ver/Paper-FOSS-Theme#4]
1. Install this app
2. Open Cyanogenmod Design App
3. Go to "symbols" on the side
4. Scroll down until you reach this app
=> CyanogenMod Design App crashs

Maybe it's better if you first do some testing before putting it on f-droid, that could have saved me 10min... 

I would love to help you out with this app, looks promising! Would you welcome (icon) contributions from other people than yourself (in contrast to 1C3), so I could bring myself in? 

Later, I can provide some logcat if needed. 

Thanks for an amswer!

**Comment by beli3ver** [comment]
Hi,

yes I see that.
I fixed it, I hope fDroid will push the next version soon.
A git command deleted a folder, thats the reason why the app crashes.

Yeah make some Icons, I would love it.
Use the GTK Paper Icon Theme as base and make your icons :-)

Sorry for that bug :-(

Thanks.
