### ISSUE TITLE
CM13 support

### ISSUE THREAD

**Issue by jumper047** [beli3ver/Paper-FOSS-Theme#9]
Please! Now there chooser  crashes, when I try to set icon theme

**Comment by beli3ver** [comment]
Yes I know.
I fixed it in the next Version. I hope FDroid will have it tomorrow.

Am 21. Juni 2016 22:43:48 MESZ, schrieb jumper047 <notifications@github.com>:
>Please! Now there chooser  crashes, when I try to set icon theme
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/beli3ver/Paper-FOSS-Theme/issues/9

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by beli3ver** [comment]
fixed #4 
fixed #9
fixed #5
